spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board_service?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1210+sun
  jpa:
    hibernate:
      ddl-auto: none
    properties.hibernate:
      format_sql: true
      show_sql: true
      jdbc:
        batch_size: 200
    open-in-view: false
