spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties.hibernate:
      format_sql: true
      show_sql: true
      jdbc:
        batch_size: 200
    open-in-view: false

  jwt:
    secret-key: ${JWT_SECRET_KEY}
    header: ${JWT_HEADER}
    prefix: ${JWT_PREFIX}
    access-exp: ${ACCESS_EXP}
    refresh-exp: ${REFRESH_EXP}